[workspace]
resolver = "2"
members = [ "internal/app_error", "internal/auth",
    "internal/content",
    "internal/infra",
    "internal/ports",
    "internal/shared",
    "internal/user",
    "server",
]
