[package]
name = "services"
version = "0.1.0"
edition = "2024"

[dependencies]
user = { path = "../user" }
shared = { path = "../shared" }
async-trait = "0.1"
mongodb = "3.2.3"
tracing = "0.1"
tokio = { version = "1.45.0", features = ["full"] }
