[package]
name = "user"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
uuid = { version = "1", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
