[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
dotenvy = "0.15"
tracing = "0.1"
mongodb = "3.2.3"
once_cell = "1.21.3"
